In [1]:
from sklearn.decomposition import PCA
import numpy as np

In [2]:
X=np.random.rand(20, 8)
X

array([[9.35906538e-01, 9.03705170e-01, 8.30897733e-01, 3.16273870e-01,
        5.51644100e-01, 6.37182923e-01, 5.40300819e-01, 2.21930618e-01],
       [9.89519306e-01, 8.62243776e-01, 1.29175975e-01, 1.93457899e-01,
        2.56022021e-01, 1.97939301e-05, 9.80791522e-02, 4.52916883e-01],
       [3.01870100e-01, 2.78748956e-01, 3.60329133e-01, 8.00149062e-01,
        2.00249960e-01, 3.16849951e-01, 8.04685233e-01, 8.99432015e-01],
       [6.13372098e-01, 3.08802915e-01, 9.93510529e-01, 6.62570785e-01,
        6.44680885e-01, 2.21609123e-01, 1.43404009e-01, 8.99968578e-01],
       [1.19950810e-01, 5.95537429e-01, 3.58093677e-01, 3.62366537e-01,
        8.56879603e-01, 7.29565435e-01, 3.61872743e-01, 3.94688869e-01],
       [2.85236221e-01, 6.64374108e-01, 4.65118698e-01, 7.70920172e-01,
        2.49677063e-01, 2.42103542e-01, 3.25721381e-01, 2.58146191e-01],
       [9.65560149e-01, 8.17316737e-01, 5.16349553e-01, 9.23383717e-01,
        2.04606475e-02, 1.84770925e-01, 1.52216826e-01, 4.

In [3]:
model=PCA(n_components=3, whiten=False) # output will be beta

In [4]:
model.fit(X)

PCA(n_components=3)

In [5]:
beta=model.transform(X)

In [6]:
beta.shape

(20, 3)

In [7]:
lamda=model.explained_variance_
lamda

array([0.16478535, 0.13437263, 0.11988568])

In [8]:
y=beta/np.sqrt(lamda)
y.shape

(20, 3)

In [9]:
y

array([[-0.73550179,  1.00775652, -0.59109548],
       [-1.52428633,  0.93176446,  0.5228514 ],
       [ 0.28100137, -1.71841069, -0.49282826],
       [-0.91394415, -1.0438707 , -0.8881002 ],
       [ 1.12569606,  0.9459471 , -0.72675005],
       [-0.10919974,  0.25730363, -0.787237  ],
       [-1.47099141,  0.73906652, -0.46664715],
       [ 1.77678934,  0.42092099, -0.77923695],
       [ 0.84116671,  1.19359434,  1.16105458],
       [-1.25319216, -0.87740253,  0.93108231],
       [ 0.05599481,  0.07101528,  1.46885426],
       [-1.10263337, -0.36714016, -1.68241207],
       [ 1.14861586,  1.75778511, -0.64811822],
       [ 1.14929487, -0.61870563,  0.0549479 ],
       [ 0.91714524, -0.3815031 ,  0.55556555],
       [-0.23226337,  0.32417276,  1.98207288],
       [ 0.03985157, -0.88436601,  1.66016784],
       [-1.02597605,  0.94344861, -0.37325626],
       [ 0.4849084 , -1.27742813, -0.77302859],
       [ 0.54752414, -1.42394837, -0.12788649]])