In [1]:
import numpy as np

In [2]:
np.random.rand(3,2)

array([[0.94157192, 0.97008571],
       [0.24109846, 0.67613509],
       [0.39133688, 0.63396119]])

In [3]:
np.random.rand(3,2)

array([[0.77997162, 0.47269464],
       [0.48969631, 0.77692154],
       [0.40889979, 0.4191942 ]])

In [4]:
np.random.seed(0)#random_state=0

In [5]:
np.random.rand(3,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [6]:
np.random.seed(0)

In [7]:
np.random.rand(3,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])