the first step is to import the numpy package <br>
we then change the package name from numpy to np

In [1]:
import numpy as np

now, we create a numpy array from a list

In [4]:
A_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(A_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
A = np.array(A_list, dtype='int32')
print(A)

[0 1 2 3 4 5 6 7 8 9]


We can directly use a list as the first argument to the function np.array 

In [6]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

a numpy array is an object, so it has a type and an id

In [8]:
type(A)

numpy.ndarray

In [9]:
id(A)

99054336

use the function len to get the length of the array

In [10]:
len(A)

10

use ArrayName.shape to get the shape/length of the array

In [11]:
A.shape

(10,)

In [12]:
type(A.shape)  # it is a tuple with one element

tuple

In [13]:
LenA = A.shape[0] # get the first/only element in the tuple
print(LenA)

10


A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
get an element of an array using ArrayName[index] <br>
index >=0, index < len(ArrayName)

In [14]:
A[0] # the first element

0

In [15]:
A[1] # the second element

1

In [16]:
A[LenA-1] # the last element

9

A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
get a sub-array using the notation ArrayName[start: end], <br>
where start >= 0, end >= 0, end > start  <br>
a.k.a array slicing

In [17]:
A[0:3] # start from A[0], then A[1], A[2], up to but not inluding A[3]

array([0, 1, 2])

In [18]:
A[1:LenA] # get elements from A[1] to A[LenA-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
A[1:] # omit end, we get elements from A[1] to A[LenA-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
A[0:0] # start == end

array([], dtype=int32)

In [21]:
A[3:0] # start < end

array([], dtype=int32)

A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
get a sub-array using the notation ArrayName[start: end: step], <br>
where start >= 0, end >= 0, end > start and step > 0 

In [22]:
A[0:3:0] # error, step is 0

ValueError: slice step cannot be zero

In [23]:
A[0:3:1] # step is 1, this is the same as A[0:3]

array([0, 1, 2])

In [24]:
A[0:3:2] # step is 2, A[0], A[2], A[4](not included, 4 > 3 in 0:3:2)

array([0, 2])

In [25]:
A[0:3:10] # step is 10, A[0], A[10](not exist)

array([0])

A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
get a sub-array using the notation ArrayName[start: end: step], <br>
where start >= 0, end >= 0, start > end and step < 0 

In [26]:
A[3:0:-1] # start is 3, end is 0, step is -1

array([3, 2, 1])

A is array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) <br>
Now, we will use negative indexes ... <br>

In [27]:
A[-1] # the last element, A[LenA-1] => A[(LenA-1)-LenA]

9

In [28]:
A[-9] # A[1] => A[1-LenA]

1

In [29]:
A[-LenA] # A[0] => A[0-LenA]

0

get a sub-array using the notation ArrayName[start: end], <br>
where start < 0, end < 0, end > start 

In [30]:
A[-9:-1] # get elements: A[-9],A[-8],A[-7],A[-6],
         #               A[-5],A[-4],A[-3],A[-2]
         # up to but not including A[-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
A[-9:] # omit end, now the last element is included in the sub-array 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
A[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

get a sub-array using the notation ArrayName[start: end: step], <br>
where start < 0, end < 0, end > start and step > 0 

In [33]:
A[-9:-1:3] # start is -9, end is -1, step is 3
           # A[-9], A[-6], A[-3], A[0](not included) 

array([1, 4, 7])

get a sub-array using the notation ArrayName[start: end: step], <br>
where start < 0, end < 0, end < start and step < 0 

In [34]:
A[-1:-9:-3]# start is -1, end is -9, step is -3
           # A[-1], A[-4], A[-7], A[-10](not exist)

array([9, 6, 3])

create an array with a predefined length <br>
initialize it with zeros or ones

In [35]:
A0 = np.zeros(10, dtype='float32')
print(A0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
A1 = np.ones(10, dtype='float32')
print(A1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


create an array with a predefined length <br>
we do not care about the initial values of the elements

In [37]:
A2 = np.empty(10)
print(A2)

[2.20178655e-316 1.82804289e-322 0.00000000e+000 0.00000000e+000
 2.44029516e-312 1.16095484e-028 4.29875484e-096 9.78750380e+199
 6.97843734e+252 2.65665585e-312]


In [38]:
A2.dtype

dtype('float64')

create an array with a predefined length <br>
initialize it with random numbers that follow a probability distribution<br>
use the functions in the module 'random' to generate random numbers <br>
rand: uniform distribution in 0~1 <br>
randn: normal distribution mean=0, std=1 <br>
(many functions in the module)

In [39]:
A_rand = np.random.rand(10)
print(A_rand)

[0.222625   0.32768059 0.17087265 0.95754324 0.50299804 0.02521101
 0.03098518 0.43967857 0.16482905 0.73261601]


In [40]:
A_randn = np.random.randn(1000)
print(A_randn)

[-5.19148621e-01 -1.49206311e+00 -9.78408017e-01  2.16243064e-02
  7.58779298e-01  1.52187916e-02  2.04463112e-01 -3.53130236e-02
 -4.26890409e-01  1.37903610e+00 -7.96562773e-01  3.56708442e-01
 -9.95274946e-01  1.40945743e+00 -1.22097893e+00 -2.75795702e+00
  1.39578207e+00 -1.20171616e+00 -7.48136697e-01 -5.62624746e-02
 -1.69390326e+00 -2.38637989e+00 -1.47576824e-03 -3.58460883e-01
  1.06773814e+00 -1.31571538e+00 -1.27772216e-01 -1.02768162e+00
 -7.49251610e-01  9.35259628e-01  1.59882422e+00  2.67916809e-01
  6.31202299e-01  1.11954976e+00 -2.36478039e+00  1.18194283e+00
  7.82519108e-02 -6.15236491e-01  1.12332383e+00  2.06416558e-01
 -7.33360670e-01 -1.53860060e-01 -5.45697759e-01  9.85314240e-01
 -9.46753421e-03 -2.94976272e-02 -6.94484848e-02 -6.87879348e-01
  7.34678905e-02  6.44969750e-01 -5.85716776e-01 -1.66960944e-02
  9.71904696e-02 -8.20860952e-01  1.39334061e+00  5.82125552e-01
  2.03478371e+00  1.40801723e+00 -4.86288542e-02  1.28180726e+00
 -3.50939397e-01 -6.73572

math functions (methods) associated with a numpy array

In [41]:
m1=A_randn.mean()
print(m1)

0.004652284217030367


In [42]:
s1=A_randn.std()
print(s1)

1.0218637936523909


save a numpy array to hard drive

In [43]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
np.save('array_A.npy',A)

load the numpy array A from hard drive

In [44]:
A1 = np.load('array_A.npy')
A1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

get a list of such methods using the function dir

In [45]:
dir(A_randn)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

more information about the methods can be found at <br> https://docs.scipy.org/doc/numpy/reference/routines.html

### Exercise

Implement a function according to the specification:
```python
def my_function(A, x):
    # parameters:
    #   A is a 1D array
    #   x is an integer
    # specification:
    #   extract the elements at even indexes in A
    #   put the extracted elements into a new 1D array B
    #   multiply each element in B by x
    #   return B
```

A test case: <br>
A = np.array([0,1,2,3,4,5,6,7,8,9,10], dtype='int64') <br>
x = 2 <br>
The function returns an array B which is array([0,4,8,12,16,20], dtype='int64')

In [46]:
#write the function
def my_function(A, x):
    LenA=A.shape[0]
    B=A[0:LenA:2]
    B*=x
    return B

In [47]:
#test the function
A = np.array([0,1,2,3,4,5,6,7,8,9,10], dtype='int64') 
x = 2
B = my_function(A, x)
B

array([ 0,  4,  8, 12, 16, 20], dtype=int64)