## Numpy Array is Tensor

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### float numbers

In [2]:
x=np.float32(1)
np.spacing(x)

1.1920929e-07

In [3]:
x=np.float32(100)
np.spacing(x)

7.6293945e-06

In [4]:
x=np.float32(1e+5)
np.spacing(x)

0.0078125

In [5]:
x=np.float32(1e+10)
np.spacing(x)

1024.0

In [6]:
x=np.float32(1e+30)
np.spacing(x)

7.5557864e+22

In [7]:
dList=[]
xList=[1, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9, 1e10]
for x in xList:
    dList.append(np.spacing(x))
plt.plot(xList, dList)
plt.xlabel('x', fontsize=16)
plt.ylabel('spacing', fontsize=16)

Text(0, 0.5, 'spacing')

In [8]:
#https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.nextafter.html
# nextafter(x1, x2)
# Return the next floating-point value after x1 towards x2
np.nextafter(0, 1, dtype='float32')

1e-45

In [9]:
np.nextafter(0, 1, dtype='float64')

5e-324

In [10]:
np.nextafter(1, 2, dtype='float32')

1.0000001

In [11]:
np.nextafter(1, 2, dtype='float64')

1.0000000000000002

In [12]:
a=np.nextafter(0, 1, dtype='float32')
b=np.nextafter(a, 1, dtype='float32')
b-a

1e-45

In [12]:
#large number + small number
np.float32('1')+np.float32('1e-8')

1.0

### Create a 1D tensor from a list

In [13]:
A_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
A_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
A = np.array(A_list, dtype=np.int32)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Directly use a list as the first argument to the function np.array 

In [15]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.int32)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

a numpy array is an object, so it has a type and an id

In [16]:
type(A)

numpy.ndarray

In [17]:
id(A)

131562512

use the function `len` to get the length of the 1D tensor

In [18]:
len(A)

10

use tensor_name.shape to get the shape of the tensor  - the preferred way

In [19]:
A.shape

(10,)

In [20]:
type(A.shape)  # it is a tuple with one element

tuple

In [21]:
LenA = A.shape[0] # get the first/only element in the tuple
LenA

10

### Create 0D, 1D, 2D, 3D, 4D, 5D tensors

define a 0D tensor (rank-0 tensor)

In [22]:
a=np.array(0.1234, dtype=np.float32)
a

array(0.1234, dtype=float32)

In [23]:
a.shape

()

define a 1D tensor (rank-1 tensor)

In [24]:
a=np.array([0.1234], dtype=np.float32)
a

array([0.1234], dtype=float32)

In [25]:
a.shape

(1,)

In [26]:
a.shape[0]

1

define a 2D tensor (rank-2 tensor)

In [27]:
a=np.array([[0.1, 0.2],
            [0.3, 0.4],
            [0.5, 0.6]], dtype=np.float32)
a

array([[0.1, 0.2],
       [0.3, 0.4],
       [0.5, 0.6]], dtype=float32)

In [28]:
a.shape

(3, 2)

In [29]:
a.shape[0]

3

define a 3D tensor (rank-3 tensor)

In [30]:
a = np.random.rand(10,9,8)
a

array([[[0.56453086, 0.89481254, 0.50554776, 0.45692319, 0.88009144,
         0.32918832, 0.94155515, 0.55692766],
        [0.42256851, 0.12224021, 0.74270532, 0.34004848, 0.88156648,
         0.2505259 , 0.63125896, 0.35011753],
        [0.67183087, 0.35858837, 0.33798747, 0.6851742 , 0.41586252,
         0.28913175, 0.90155329, 0.88412644],
        [0.24662273, 0.84450258, 0.61507977, 0.17937406, 0.49610749,
         0.42757228, 0.36834925, 0.21918532],
        [0.41962377, 0.34168983, 0.02598188, 0.58665982, 0.82027619,
         0.88307106, 0.36865841, 0.44532182],
        [0.06634159, 0.67234221, 0.71101564, 0.45357669, 0.67604974,
         0.91071161, 0.63939195, 0.029637  ],
        [0.93616752, 0.99462447, 0.73638884, 0.85473306, 0.11177663,
         0.3267319 , 0.39957783, 0.7922977 ],
        [0.98564107, 0.2192756 , 0.20100929, 0.986655  , 0.07747158,
         0.2221483 , 0.2596505 , 0.84129564],
        [0.32525885, 0.17257629, 0.0895855 , 0.94767526, 0.93108269,
         0.

In [31]:
a.shape

(10, 9, 8)

In [32]:
a.shape[0]

10

define a 4D tensor (rank-4 tensor)

In [33]:
a = np.zeros((10,128,128,3), dtype=np.float32)

In [34]:
a.shape

(10, 128, 128, 3)

define a 5D tensor (rank-5 tensor)

In [35]:
a = np.ones((10,3,128,128,128), dtype=np.float32)

In [36]:
a.shape

(10, 3, 128, 128, 128)

### Create Special Tensors

In [37]:
A0 = np.zeros(10, dtype='float32')
A0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [38]:
A1 = np.ones(10, dtype='float32')
A1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [39]:
# create an empty tensory with a predefined length
# we do not care about the initial values of the elements
A2 = np.empty(10)
A2

array([ 57.08363634,  82.99299605, 108.90235576, 134.81171548,
       160.72107519, 186.6304349 , 212.53979461, 238.44915433,
       264.35851404, 260.64      ])

In [40]:
A_rand = np.random.rand(10) # uniform distribution in 0~1 
A_rand

array([0.57563076, 0.54799939, 0.21390488, 0.83790268, 0.32779241,
       0.28666025, 0.39036459, 0.72222988, 0.20162724, 0.51947661])

In [41]:
A_randn = np.random.randn(1000) # normal distribution with mean=0, std=1 
A_randn

array([ 3.32177548e-01, -1.15450664e+00,  5.03053147e-01, -1.53098713e-01,
       -4.04843762e-01, -2.64366131e-01,  8.28119263e-01, -6.65574950e-01,
       -1.95563110e+00, -1.22187435e+00, -2.45071998e-01,  7.50684837e-02,
        1.18805083e+00,  1.12770504e+00,  1.18625584e-01, -1.24157774e+00,
       -1.16664700e-01,  6.09196676e-01, -9.20802085e-01, -1.31702286e+00,
       -8.15935933e-01, -1.31271387e+00, -1.00014963e+00, -9.19242590e-01,
       -5.75645248e-01, -1.14846244e+00,  6.51747794e-01, -1.57554974e+00,
       -1.03090680e+00,  1.21897236e+00, -1.00353846e-01,  4.05803438e-01,
       -1.47883311e-01,  6.78833451e-01, -4.07990582e-01, -9.25583332e-01,
        1.33167664e+00, -1.38415172e+00, -5.86274292e-01, -3.65675563e-01,
       -1.40046581e+00, -4.89085199e-02,  1.47248673e+00,  2.03574023e+00,
       -1.20295054e+00, -2.45029426e-01,  1.60812734e+00, -1.38319843e+00,
        1.15094136e+00,  2.57938553e-01,  1.49652739e+00,  6.75385873e-01,
        3.27687964e-01, -

In [42]:
A0 = np.arange(0, 10, 2, dtype='int32')
A0

array([0, 2, 4, 6, 8])

In [43]:
A1 = np.linspace (0, 1, 5)
A1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Reshape a tensor: change the 'shape' of a tensor and keep the order of the elements
after `B=A.reshape()`, B and A share the same data in computer memory `in most cases`

In [44]:
A = np.array([[0, 1, 2, 3], 
              [4, 5, 6, 7] ])
A.shape

(2, 4)

In [45]:
B1 = A.reshape(1,8)
B1

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [46]:
B1.shape

(1, 8)

In [47]:
B2 = A.reshape(8)
B2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
B2.shape

(8,)

In [49]:
A = np.array([[0, 1,  2, 3], 
              [4, 5, 6, 7] ])
B1 = A.reshape(1,8)
B1[0]=100 # is it the first element in B ?
A

array([[100, 100, 100, 100],
       [100, 100, 100, 100]])

In [50]:
A = np.array([[0, 1,  2, 3], 
              [4, 5, 6, 7] ])
B1 = A.reshape(1,8)
B1[0,0]=100
A

array([[100,   1,   2,   3],
       [  4,   5,   6,   7]])

### Repeat elements of a tensor
see the solution of homework 1 part 2 task 1

In [51]:
A = np.array([[0, 1,  2, 3]])
A.shape

(1, 4)

In [52]:
B=A.repeat(2, axis=0)
B

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [53]:
B=A.repeat(2, axis=1)
B

array([[0, 0, 1, 1, 2, 2, 3, 3]])

In [54]:
B=A[[0,0,0,0],:]
B

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [55]:
B.shape

(4, 4)

### Swap axes/dimensions

In [56]:
A = np.array([[0, 1,  2, 3], 
              [4, 5, 6, 7] ])
B=A.transpose(1,0)
B

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [57]:
A = np.array([[0, 1,  2, 3], 
              [4, 5, 6, 7] ])
B=A.transpose(1,0)
B[0,0]=100
A

array([[100,   1,   2,   3],
       [  4,   5,   6,   7]])

In [58]:
A = np.array([[0, 1,  2, 3], 
              [4, 5, 6, 7] ])
B=A.transpose(0,1)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [59]:
A = np.array([[[0, 1], [2, 3]], 
              [[4, 5], [6, 7]],
              [[8, 9], [10, 11]]])
A

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [60]:
A.shape

(3, 2, 2)

In [61]:
B=A.transpose(0,2,1)
B

array([[[ 0,  2],
        [ 1,  3]],

       [[ 4,  6],
        [ 5,  7]],

       [[ 8, 10],
        [ 9, 11]]])

In [62]:
B=A.transpose(1,0,2)
B

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

In [63]:
B=A.transpose(2,1,0) # B[k,j,i] is A[i,j,k]
B

array([[[ 0,  4,  8],
        [ 2,  6, 10]],

       [[ 1,  5,  9],
        [ 3,  7, 11]]])

In [64]:
B=A.transpose(2,1,0) # B[k,j,i] is A[i,j,k]
for i in range(0, A.shape[0]):
    for j in range(0, A.shape[1]):
        for k in range(0, A.shape[2]):
            print(A[i,j,k], B[k,j,i])

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11


In [65]:
A = np.array([[[0, 1], [2, 3]], 
              [[4, 5], [6, 7]],
              [[8, 9], [10, 11]]])
B=A.transpose(2,1,0) # B[k,j,i] is A[i,j,k]
# a 'view' of A is returned whenever possible.
B[0,0,0]=100
A

array([[[100,   1],
        [  2,   3]],

       [[  4,   5],
        [  6,   7]],

       [[  8,   9],
        [ 10,  11]]])

### Element indexing

get an element of a tensor using tensor_name[element_index]

In [66]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
A[0] # the first element

0

In [68]:
A[1] # the second element

1

In [69]:
A[A.shape[0]-1] # the last element

9

In [70]:
A[-1] # the last element, A[LenA-1] => A[(LenA-1)-LenA], LenA=A.shape[0]

9

In [71]:
A[-9] # A[1] => A[1-LenA]

1

In [72]:
A[-A.shape[0]] # A[0] => A[0-LenA]

0

### Slicing a tesor to get a sub-tensor

get a sub-tensor using the notation tensor_name[start: end], <br>

In [73]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[0:3] # start from A[0], then A[1], A[2], up to but not inluding A[3]

array([0, 1, 2])

In [75]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[1:A.shape[0]] # get elements from A[1] to A[LenA-1], LenA is A.shape[0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[1:] # omit end, we get elements from A[1] to A[LenA-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[0:0] # start == end

array([], dtype=int32)

In [78]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[3:0] # start < end

array([], dtype=int32)

In [79]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
#A[0:3:0] # error, step is 0

In [80]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[0:3:1] # step is 1, this is the same as A[0:3]

array([0, 1, 2])

In [81]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[0:3:2] # step is 2, A[0], A[2], A[4](not included, 4 > 3 in 0:3:2)

array([0, 2])

In [82]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[0:3:10] # step is 10, A[0], A[10](not exist)

array([0])

In [83]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[3:0:-1] # start is 3, end is 0, step is -1

array([3, 2, 1])

In [84]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[-9:-1] # get elements: A[-9],A[-8],A[-7],A[-6],
         #               A[-5],A[-4],A[-3],A[-2]
         # up to but not including A[-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[-9:] # omit end, now the last element is included in the sub-array 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[-9:-1:3] # start is -9, end is -1, step is 3
           # A[-9], A[-6], A[-3], A[0](not included) 

array([1, 4, 7])

In [88]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
A[-1:-9:-3]# start is -1, end is -9, step is -3
           # A[-1], A[-4], A[-7], A[-10](not exist)

array([9, 6, 3])

### Get a sub-tensor of a tensor using slicing or indexlists

In [89]:
A = np.array([0, 1, 2, 3, 4, 5], dtype='int64')
B=A[0:1] # slicing
B

array([0], dtype=int64)

In [90]:
B[0]=100
A

array([100,   1,   2,   3,   4,   5], dtype=int64)

In [91]:
A = np.array([0, 1, 2, 3, 4, 5], dtype='int64')
IndexList=[0]
B = A[IndexList]

In [92]:
B[0] = 100
A

array([0, 1, 2, 3, 4, 5], dtype=int64)

### Concatenate more than two tensors into one tensor

In [93]:
x1 = np.array([ [1, 2,  3, 4], 
                [3, 4, 5, 6] ])
x2 = np.array([ [5, 6, 7, 8],  
                [7, 8, 9, 10],
                [8, 9, 10, 11] ])
x3=np.concatenate([x1,x2], axis=0)
x3

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11]])

In [94]:
x4=np.concatenate([x1,x2,x3], axis=0)
x4

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11]])

### Aggregation functions

In [95]:
A1 = np.random.randn(1000)

In [96]:
A1.mean()

0.024460097100026668

In [97]:
A1.std()

1.043079859108461

In [98]:
A1.sum()

24.46009710002667

In [99]:
A2 = np.random.rand(10, 2)
A2

array([[0.15256262, 0.62855697],
       [0.78833643, 0.76083212],
       [0.62929193, 0.45724506],
       [0.02228608, 0.85704838],
       [0.54820414, 0.6046921 ],
       [0.0669048 , 0.94526612],
       [0.12771791, 0.99174122],
       [0.1350068 , 0.72381019],
       [0.18527458, 0.51072915],
       [0.56235501, 0.86847362]])

In [100]:
A2.sum(axis=0)

array([3.2179403 , 7.34839493])

In [101]:
A2.sum(axis=1)

array([0.78111959, 1.54916855, 1.086537  , 0.87933445, 1.15289624,
       1.01217092, 1.11945912, 0.85881698, 0.69600374, 1.43082863])

In [102]:
A2.min(axis=0)

array([0.02228608, 0.45724506])

In [103]:
A2.max(axis=0)

array([0.78833643, 0.99174122])

what is A.sum(axis=m) ?

In [4]:
A=np.random.rand(4,3,2)
A.shape

(4, 3, 2)

In [12]:
A

array([[[0.2577545 , 0.6775452 ],
        [0.82944366, 0.41433448],
        [0.40195405, 0.56211843]],

       [[0.3827123 , 0.73247428],
        [0.71064589, 0.91077745],
        [0.98860965, 0.50062854]],

       [[0.3100307 , 0.60454791],
        [0.5164631 , 0.11461095],
        [0.10330168, 0.73710976]],

       [[0.06672872, 0.23378279],
        [0.78733318, 0.48678932],
        [0.79291931, 0.07358404]]])

In [6]:
A0=A[:,:,0]
A0.shape

(4, 3)

In [7]:
A1=A[:,:,1]
A1.shape

(4, 3)

In [11]:
A0+A1

array([[0.93529969, 1.24377814, 0.96407248],
       [1.11518658, 1.62142335, 1.48923818],
       [0.91457861, 0.63107406, 0.84041144],
       [0.30051152, 1.2741225 , 0.86650336]])

In [10]:
B=A.sum(axis=2)
B

array([[0.93529969, 1.24377814, 0.96407248],
       [1.11518658, 1.62142335, 1.48923818],
       [0.91457861, 0.63107406, 0.84041144],
       [0.30051152, 1.2741225 , 0.86650336]])

In [14]:
n0=5; n1=4; n2=3; n3=2
A = np.random.rand(5, 4, 3, 2)
A.sum(axis=2) 

array([[[0.10990821, 0.9564406 ],
        [1.83171861, 0.67761678],
        [1.66174763, 2.1739255 ],
        [1.99197754, 1.59737959]],

       [[1.04457036, 0.37310588],
        [1.36428384, 0.84837124],
        [2.10757713, 1.40686382],
        [1.49144364, 0.52020307]],

       [[2.19610034, 1.59821925],
        [1.86032926, 0.62209634],
        [0.80530882, 1.29792643],
        [1.50469686, 0.85136183]],

       [[1.56749584, 1.28622807],
        [2.54104803, 1.75864876],
        [2.23429904, 1.37144789],
        [1.00290811, 1.59738086]],

       [[1.35532336, 1.77883428],
        [0.69710288, 1.76804955],
        [2.17529211, 2.39599074],
        [1.33279103, 1.53098648]]])

In [15]:
B=np.zeros((n0, n1,n3))
for m in range(0, n2):
     B+=A[:, :, m]
B

array([[[0.10990821, 0.9564406 ],
        [1.83171861, 0.67761678],
        [1.66174763, 2.1739255 ],
        [1.99197754, 1.59737959]],

       [[1.04457036, 0.37310588],
        [1.36428384, 0.84837124],
        [2.10757713, 1.40686382],
        [1.49144364, 0.52020307]],

       [[2.19610034, 1.59821925],
        [1.86032926, 0.62209634],
        [0.80530882, 1.29792643],
        [1.50469686, 0.85136183]],

       [[1.56749584, 1.28622807],
        [2.54104803, 1.75864876],
        [2.23429904, 1.37144789],
        [1.00290811, 1.59738086]],

       [[1.35532336, 1.77883428],
        [0.69710288, 1.76804955],
        [2.17529211, 2.39599074],
        [1.33279103, 1.53098648]]])

### Basic Math Operations (+ - * ** /)

In [104]:
A = np.array([[0, 1, 2], 
              [3, 4, 5]], dtype='float32')
B=A+10
B

array([[10., 11., 12.],
       [13., 14., 15.]], dtype=float32)

In [105]:
A = np.array([[0, 1, 2], 
              [3, 4, 5]], dtype='float32')
B=A*10
B

array([[ 0., 10., 20.],
       [30., 40., 50.]], dtype=float32)

In [106]:
A = np.array([[0, 1, 2], 
              [3, 4, 5]], dtype='float32')
B=A/10
B

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5]], dtype=float32)

In [107]:
A = np.array([[0, 1, 2], 
              [3, 4, 5]], dtype='float32')
B = np.array([[1, 1, 1], 
              [2, 2, 2]], dtype='int64')
C=A+B
C

array([[1., 2., 3.],
       [5., 6., 7.]])

In [108]:
C.dtype

dtype('float64')

In [109]:
A = np.array([[0, 1, 2], 
              [3, 4, 5]], dtype='float32')
B = np.array([[1, 1, 1], 
              [2, 2, 2]], dtype='float32')
A-B

array([[-1.,  0.,  1.],
       [ 1.,  2.,  3.]], dtype=float32)

In [110]:
A = np.array([[0, 1, 2], 
              [3, 4, 5]], dtype='float32')
B = np.array([[1, 1, 1], 
              [2, 2, 2]], dtype='float32')
A*B

array([[ 0.,  1.,  2.],
       [ 6.,  8., 10.]], dtype=float32)

matrix multiplication

In [111]:
A=np.random.rand(3,10)
B=np.random.rand(10,3)
#C=A*B

In [112]:
A=np.random.rand(3,10)
B=np.random.rand(10,3)
C=np.matmul(A, B) # or C=np.dot(A,B)
C

array([[1.93532563, 3.70058815, 3.18056971],
       [1.15452827, 1.94178877, 1.56252871],
       [1.44062307, 2.05237856, 2.36868755]])

matrix inverse

In [13]:
A = np.array([[1, 1, 2], 
              [3, 4, 5],
              [6, 7, 8]], dtype='float64')
B = np.linalg.inv(A)
B

array([[ 1.        , -2.        ,  1.        ],
       [-2.        ,  1.33333333, -0.33333333],
       [ 1.        ,  0.33333333, -0.33333333]])

### Broadcasting

In [113]:
A=np.array([0, 1,2,3])
B=1
A+B

array([1, 2, 3, 4])

In [114]:
A = np.array([ [0,   0,   0], 
               [10, 10, 10],
               [30, 30, 30]])
B = np.array([[0, 1, 2]])
C = A + B
C

array([[ 0,  1,  2],
       [10, 11, 12],
       [30, 31, 32]])

In [115]:
A.shape

(3, 3)

In [116]:
B.shape

(1, 3)

### save a tensor to hard drive, and load a tensor from hard drive

In [117]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int32')
np.save('array_A.npy',A)

load the tensor A from hard drive

In [118]:
A1 = np.load('array_A.npy')
A1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Example: calculate the distances between points in array A and a single point B in 3D space

In [119]:
A = np.array([[0, 0, 0],
              [1, 0, 0],
              [0, 1, 0],
              [1, 1, 0],
              [0, 0, 1],
              [1, 0, 1],
              [0, 1, 1],
              [1, 1, 1]],
dtype='float64')
B = np.array([2, 2, 2], dtype='float64')

In [120]:
#use a for loop
dist = np.zeros(8, dtype='float64')
for n in range(0, 8):
    d = A[n,:] - B # displacement
    dist[n] = np.sqrt(np.sum(d**2))
dist

array([3.46410162, 3.        , 3.        , 2.44948974, 3.        ,
       2.44948974, 2.44948974, 1.73205081])

In [121]:
#two lines of code
D = A - B
dist = np.sqrt(np.sum(D**2, axis=1))
dist

array([3.46410162, 3.        , 3.        , 2.44948974, 3.        ,
       2.44948974, 2.44948974, 1.73205081])

### get a list of methods using the function dir

In [122]:
dir(A)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

more information about the methods can be found at <br> https://docs.scipy.org/doc/numpy/reference/routines.html

### Exercise-1

Implement a function according to the specification:
```python
def my_function(x, w, b):
    # parameters:
    #   x is a 1D tensor, and the number of elements is an even number
    #   w is a 1D tensor, w.shape[0] is x.shape[0]/2
    #   b is a scalar
    # specification:
    #   extract the elements in x at even indexes (0, 2, 4, ...) 
    #   put the extracted elements into a new tensor x1
    #   perform element-wise multiplication between x1 and w, and we get a new tensor x2
    #   add b to every element of the tensor x2, and then we get a new tensor x3
    #   return x3
```

A test case: <br>
x = np.array([0,1,2,3,4,5,6,7,8,9], dtype='float32') <br>
w = np.array([0,1,2,3,4], dtype='float32')  <br>
b = 10  <br>
y = my_function(x, w, b)  <br>
y is array([10., 12., 18., 28., 42.], dtype=float32) <br>

In [132]:
#write the function using loop
def my_function(x, w, b):    
    x1 = []
    for n in range(0, x.shape[0], 2):
        x1.append(x[n])
    x1=np.array(x1, dtype=x.dtype)
    x2=np.zeros(x1.shape, dtype=x.dtype)
    for n in range(0, x1.shape[0]):
        x2[n]=x1[n]*w[n]
    x3=np.zeros(x2.shape, dtype=x.dtype)
    for n in range(0, x2.shape[0]):
        x3[n]=x2[n]+b    
    return x3

In [ ]:
#write the function using vectorized operations
def my_function(x, w, b):    
    x1 = x[0:x.shape[0]:2]
    x2 = x1*w
    x3 = x2+b
    return x3

In [133]:
#test the function
x = np.array([0,1,2,3,4,5,6,7,8,9], dtype='float32') 
w = np.array([0,1,2,3,4], dtype='float32') 
b = 10
y = my_function(x, w, b)
y

array([10., 12., 18., 28., 42.], dtype=float32)

### Exercise-2

We have a data matrix `X`. Each row of `X` is a data point <br>
Then we need to do some pre-precessing <br>
(1) compute the sample mean `x_mean`, which can be done using the aggregation function `mean` <br>
(2) subtract the sample mean from each data sample/point, which can be done using Broadcasting

In [3]:
X=np.random.rand(100,2)
X.dtype

dtype('float64')

In [4]:
# use a loop to get x_mean
x_mean=np.zeros(2)
for n in range(0, X.shape[0]):
    x_mean+=X[n]
x_mean/= X.shape[0]   
x_mean

array([0.51916921, 0.45188632])

In [5]:
x_mean=X.mean(axis=0)
x_mean

array([0.51916921, 0.45188632])

In [128]:
x_mean.shape

(2,)

In [8]:
# use a loop to subtract the sample mean from each data sample
Xnew=np.zeros((100,2))
for n in range(0, X.shape[0]):
    Xnew[n]=X[n]-x_mean

In [9]:
Xnew

array([[-0.03637546, -0.09349182],
       [-0.49851561, -0.19059958],
       [-0.1050614 ,  0.33787874],
       [-0.05744641, -0.12909054],
       [-0.11730627, -0.04618642],
       [-0.04385928, -0.34036383],
       [-0.02184157,  0.49953818],
       [ 0.41718346, -0.40505436],
       [-0.00196589,  0.25260943],
       [ 0.14834006,  0.18473643],
       [-0.09822371,  0.4652261 ],
       [ 0.40468536, -0.41210976],
       [-0.40725373,  0.21536563],
       [ 0.44684288, -0.28552443],
       [-0.33097827, -0.07505861],
       [-0.11726467, -0.07181762],
       [-0.17679923,  0.25547174],
       [ 0.05064533, -0.33721562],
       [ 0.1765935 ,  0.12408092],
       [ 0.18124029, -0.11028713],
       [-0.1890061 , -0.13249106],
       [-0.05311119, -0.35554805],
       [-0.20731589, -0.34630876],
       [-0.4234858 ,  0.38175862],
       [-0.50984596,  0.23080925],
       [-0.20599188,  0.12093412],
       [-0.16914825, -0.33927613],
       [-0.17942687,  0.0801232 ],
       [-0.48268236,

In [10]:
Xnew=X-x_mean
Xnew.shape

(100, 2)

In [11]:
Xnew

array([[-0.03637546, -0.09349182],
       [-0.49851561, -0.19059958],
       [-0.1050614 ,  0.33787874],
       [-0.05744641, -0.12909054],
       [-0.11730627, -0.04618642],
       [-0.04385928, -0.34036383],
       [-0.02184157,  0.49953818],
       [ 0.41718346, -0.40505436],
       [-0.00196589,  0.25260943],
       [ 0.14834006,  0.18473643],
       [-0.09822371,  0.4652261 ],
       [ 0.40468536, -0.41210976],
       [-0.40725373,  0.21536563],
       [ 0.44684288, -0.28552443],
       [-0.33097827, -0.07505861],
       [-0.11726467, -0.07181762],
       [-0.17679923,  0.25547174],
       [ 0.05064533, -0.33721562],
       [ 0.1765935 ,  0.12408092],
       [ 0.18124029, -0.11028713],
       [-0.1890061 , -0.13249106],
       [-0.05311119, -0.35554805],
       [-0.20731589, -0.34630876],
       [-0.4234858 ,  0.38175862],
       [-0.50984596,  0.23080925],
       [-0.20599188,  0.12093412],
       [-0.16914825, -0.33927613],
       [-0.17942687,  0.0801232 ],
       [-0.48268236,